//
// Created by Samuel Jones on 12/21/21.
//

#ifndef BADGE_C_PINOUT_RP2040_H
#define BADGE_C_PINOUT_RP2040_H

#include "hardware/gpio.h"
#include "hardware/spi.h"

#define BADGE_GPIO_BTN_A (1)
#define BADGE_GPIO_BTN_B (2)

#define BADGE_PIO_IR (pio0)
#define BADGE_GPIO_IR_RX (0)
#define BADGE_GPIO_IR_TX (3)

#define BADGE_GPIO_LED_GREEN (5) // PWM2 B
#define BADGE_GPIO_LED_RED (6) // PWM3 A
#define BADGE_GPIO_LED_BLUE (4) // PWM2 A

#define BADGE_GPIO_BTN_RECORD (7)
#define BADGE_GPIO_BTN_PLAY (8)

#define BADGE_SPI_DISPLAY (spi1)
#define BADGE_GPIO_DISPLAY_CS (9)
#define BADGE_GPIO_DISPLAY_SCK (10)
#define BADGE_GPIO_DISPLAY_MOSI (11)
#define BADGE_GPIO_DISPLAY_DC (12)
#define BADGE_GPIO_DISPLAY_RESET (13)
#define BADGE_GPIO_DISPLAY_BACKLIGHT (14) // PWM7 A

#define BADGE_GPIO_BTN_FASTFORWARD (15)
#define BADGE_GPIO_BTN_STOP_EJECT (16)
#define BADGE_GPIO_BTN_REWIND (17)

#define BADGE_I2C_AUDIO_CODEC (i2c1)
#define BADGE_I2C_AUDIO_CODEC_BAUD (100000) // 100 kHz
#define BADGE_I2C_AUDIO_CODEC_ADDR (0x1A)
#define BADGE_PIO_AUDIO_CODEC (pio1)
#define BADGE_GPIO_AUDIO_CODEC_SDA (18)
#define BADGE_GPIO_AUDIO_CODEC_SCL (19)
#define BADGE_GPIO_AUDIO_CODEC_MCLK (20)
#define BADGE_GPIO_AUDIO_CODEC_BCLK (21)
#define BADGE_GPIO_AUDIO_CODEC_FS (22)
#define BADGE_GPIO_AUDIO_CODEC_DACIN (23)
#define BADGE_GPIO_AUDIO_CODEC_ADCOUT (24)

#define BADGE_GPIO_DPAD_UP (25)
#define BADGE_GPIO_DPAD_LEFT (26)
#define BADGE_GPIO_DPAD_DOWN (27)
#define BADGE_GPIO_DPAD_RIGHT (28)

#define BADGE_GPIO_ADC_VOLUME (29)

#endif //BADGE_C_PINOUT_RP2040_H
