[book]
authors = ["Dustin Firebaugh"]
language = "en"
multilingual = false
src = "src"
title = "HackRVA Badge"

[output]
[output.html]
additional-css = []
default-theme = "dark"
edit-url-template = ""
github-repo-icon = "fa-github"
github-repo-url = "https://github.com/hackrva/badge2025/"
hide-sidebar = false
site-url = ""
additional-js= ["wasm-simulator.js", "badge-history.js"]
