// Auto-generated by boost-eee-o
// Total notes: 162
// Duration: 22000ms

#include <music.h>
#include <audio.h>
#include <utils.h>

static const struct audio_out_note RIB_THEME_NOTES[] = {
	{
		.v = 0,
		.ms = 0,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 0,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F5,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 0,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As4,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 0,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D5,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 0,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As2,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 1000,
		.spec = {
			.callback = NULL,
			.frequency_hz = 24000,
			.duration_ms = 2000,
			.envelope = AUDIO_OUT_ENVELOPE_SLOW_FADE_OUT,
			.phase = 0,
			.amplitude_dBFS = -9,
			.restart = true,
			.type = AUDIO_OUT_TYPE_NES_NOISE,
			.nes_noise.lfsr_val = 0x1234,
			.nes_noise.mode_flag = false,
		}
	},
	{
		.v = 4,
		.ms = 1000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1055.5555555555557,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_B3,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1111.111111111111,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1166.6666666666667,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs4,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1222.2222222222222,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As4,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1277.7777777777778,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_B4,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1333.3333333333335,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds5,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1388.888888888889,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs5,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1444.4444444444446,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_B5,
			.duration_ms = 55,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 1500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 2000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 2000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 2000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 2000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs5,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 2000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A3,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 2000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds3,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 2000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C3,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 2333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 2333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 2333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 2333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs5,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 2333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 2333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 2333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 2666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 2666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 2666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 2666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs5,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 2666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 2666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 2666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 3000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 3000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 3000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs5,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 3000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 3000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 3000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 3333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 3333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 3333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs5,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 3333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 3333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 3333.333333333333,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 3666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 3666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds6,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 3666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs5,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 3666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 3666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 3666.6666666666665,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C4,
			.duration_ms = 333,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 4000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 4000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As2,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 4000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 4000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 4000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 4500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 4500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 4500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 4500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 4500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 5000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 5000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 5000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 5000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 5000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 5500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 5500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds3,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Cs6,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 5500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 5500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_G5,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 5500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Cs5,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 6000,
		.spec = {
			.callback = NULL,
			.frequency_hz = 24000,
			.duration_ms = 2000,
			.envelope = AUDIO_OUT_ENVELOPE_SLOW_FADE_OUT,
			.phase = 0,
			.amplitude_dBFS = -9,
			.restart = true,
			.type = AUDIO_OUT_TYPE_NES_NOISE,
			.nes_noise.lfsr_val = 0x1234,
			.nes_noise.mode_flag = false,
		}
	},
	{
		.v = 4,
		.ms = 6500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 6500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 6500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 6500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_G5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 6500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 6500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_G3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 7000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Cs4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 7000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_E6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 7000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 7000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 7000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_E5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 7000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 7000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 7500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D4,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 7500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F6,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 7500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D6,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 7500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 7500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F5,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 7500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As3,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 7500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F3,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 8000,
		.spec = {
			.callback = NULL,
			.frequency_hz = 24000,
			.duration_ms = 2000,
			.envelope = AUDIO_OUT_ENVELOPE_SLOW_FADE_OUT,
			.phase = 0,
			.amplitude_dBFS = -9,
			.restart = true,
			.type = AUDIO_OUT_TYPE_NES_NOISE,
			.nes_noise.lfsr_val = 0x1234,
			.nes_noise.mode_flag = false,
		}
	},
	{
		.v = 4,
		.ms = 8500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 8500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 8500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 8500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 8500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 8500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 8500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As2,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 9000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 9000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 9000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 9000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 9000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 9000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 9000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As2,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 9500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 9500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 9500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 9500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A3,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 9500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds3,
			.duration_ms = 1000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 10000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 10000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 10000,
		.spec = {
			.callback = NULL,
			.frequency_hz = 24000,
			.duration_ms = 2000,
			.envelope = AUDIO_OUT_ENVELOPE_SLOW_FADE_OUT,
			.phase = 0,
			.amplitude_dBFS = -9,
			.restart = true,
			.type = AUDIO_OUT_TYPE_NES_NOISE,
			.nes_noise.lfsr_val = 0x1234,
			.nes_noise.mode_flag = false,
		}
	},
	{
		.v = 6,
		.ms = 10250,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs4,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 10500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 10500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 10500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 10500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C5,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 10500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A4,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 10500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 11000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F5,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 11000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds5,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 11000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_B4,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 11000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_A4,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 11000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F3,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 11000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F4,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 11000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_C3,
			.duration_ms = 2000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 13000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F5,
			.duration_ms = 7000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 1,
		.ms = 13000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_D5,
			.duration_ms = 7000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 2,
		.ms = 13000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As4,
			.duration_ms = 7000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 3,
		.ms = 13000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F4,
			.duration_ms = 7000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 5,
		.ms = 13000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F3,
			.duration_ms = 7000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 4,
		.ms = 13000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As3,
			.duration_ms = 7000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 6,
		.ms = 13000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As2,
			.duration_ms = 7000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 13250,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 13500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_G6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 13750,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 14000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 14500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs6,
			.duration_ms = 500,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 15250,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 15500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_G6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 15750,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 16000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 16250,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 16500,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 16750,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_G6,
			.duration_ms = 250,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 17000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_F6,
			.duration_ms = 3000,
			.envelope = 0,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 7,
		.ms = 20000,
		.spec = {
			.callback = NULL,
			.frequency_hz = 24000,
			.duration_ms = 2000,
			.envelope = AUDIO_OUT_ENVELOPE_SLOW_FADE_OUT,
			.phase = 0,
			.amplitude_dBFS = -9,
			.restart = true,
			.type = AUDIO_OUT_TYPE_NES_NOISE,
			.nes_noise.lfsr_val = 0x1234,
			.nes_noise.mode_flag = false,
		}
	},
	{
		.ms = 22000,
		.spec = {
			.type = AUDIO_OUT_TYPE_NONE,
		}
	}
};

const struct audio_out_section RIB_THEME = {
	.length = ARRAY_SIZE(RIB_THEME_NOTES),
	.notes = RIB_THEME_NOTES,
	.next = NULL,
};
