// Auto-generated by boost-eee-o
// Total notes: 45
// Duration: 7031.25ms

#include <music.h>
#include <audio.h>
#include <utils.h>

static const struct audio_out_note RIB_INTRO_NOTES[] = {
	{
		.v = 0,
		.ms = 0,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 992,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 999,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 509,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 1508,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 375,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 1883,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 375,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 2258,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 267,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 2541,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 187,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 2750,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 175,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 2950,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 125,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3101.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 85,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3221,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 145,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3383,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3476.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3570.5,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3664.25,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3758,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3851.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 3945.5,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4039.25,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4133,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4226.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4320.5,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4414.25,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4508,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4601.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4695.5,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 120,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4816,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 120,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 4957,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 120,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5084,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 183,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5275,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs3,
			.duration_ms = 256,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5531.25,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5625,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5718.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_B3,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5812.5,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Cs4,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 5906.25,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds4,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6000,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_E4,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6093.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs4,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6187.5,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs4,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6281.25,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As4,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6375,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_B4,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6468.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Cs5,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6562.5,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Ds5,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6656.25,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_E5,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6750,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Fs5,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6843.75,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_Gs5,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.v = 0,
		.ms = 6937.5,
		.spec = {
			.callback = NULL,
			.frequency_hz = NOTE_As5,
			.duration_ms = 93,
			.envelope = AUDIO_OUT_ENVELOPE_NONE,
			.phase = 0,
			.amplitude_dBFS = -12,
			.restart = true,
			.type = AUDIO_OUT_TYPE_SQUARE,
			.square.duty_cycle = UINT8_MAX / 2,
		}
	},
	{
		.ms = 7031.25,
		.spec = {
			.type = AUDIO_OUT_TYPE_NONE,
		}
	}
};

const struct audio_out_section RIB_INTRO = {
	.length = ARRAY_SIZE(RIB_INTRO_NOTES),
	.notes = RIB_INTRO_NOTES,
	.next = NULL,
};
